name: mimic
stages:
  # - name: filter_codes
  #   params:
  #     codes_to_remove:
  #       - INFUSION_
  #       - SUBJECT_WEIGHT_AT_INFUSION
  #       - Weight
  #       - Height
  #       - eGFR
  #       - PROCEDURE//START
  #       - PROCEDURE//END
  #       - MEDICATION//START//
  #       - SUBJECT_FLUID_OUTPUT//
  #     is_prefix: true

  - name: preprocessing
    transforms:
      # - LabData.retain_only_test_with_numeric_result # Done in extract_MIMIC
      # - TransferData.retain_only_transfer_and_admit_types # TODO in extract_MIMIC
      # - DemographicData.retrieve_demographics_from_hosp_adm # No longer treated as static variables
      - DemographicData.process_race
      - DemographicData.process_marital_status
      # - InpatientData.process_drg_codes # Already filtered to HCFA codes in extract_MIMIC
      - InpatientData.process_hospital_admissions
      - InpatientData.process_hospital_discharges # must be before processing diagnoses
      # - HCPCSData.unify_names # Pass through so not needed
    vocab: ${vocab}

  - name: CodeCounter
    agg_to: ${output_dir}/${code_counts_fn}
    skip: ${is_not_null:${vocab}}

  - name: preprocessing_with_counts
    transforms:
      - LabData.make_quantiles
    params:
      counts: ${output_dir}/${code_counts_fn}
    vocab: ${vocab}

  - name: preprocessing
    transforms:
      - DeathData.place_death_before_dc_if_same_time
      # - PatientFluidOutputData.make_quantiles # Not included in MEDS schema
      # - BMIData.make_quantiles # BMI dealt with as simple measurement
      - EdData.process_ed_registration
      - EdData.process_ed_acuity
      - MeasurementData.process_simple_measurements
      - MeasurementData.process_pain
      # - MeasurementData.process_blood_pressure # Treat as simple measurements now systolic and diastolic are processed seperately
    vocab: ${vocab}

  - name: preprocessing_with_num_quantiles
    transforms:
      - ICUStayData.process # No SOFA scores added
    vocab: ${vocab}

  - name: Quantizator
    params:
      code_prefixes:
        - EMERGENCY_DEPARTMENT_VITAL_SIGNS//Q
        - EMERGENCY_DEPARTMENT_TRIAGE//Q
        - OBSERVATION_MEDICAL_RECORD//Q
        # - SUBJECT_FLUID_OUTPUT//Q// # Not included in MEDS schema
    agg_to: ${output_dir}/${quantiles_fn}
    agg_params:
      num_quantiles: ${num_quantiles}
    skip: ${is_not_null:${vocab}}

  - name: transform_to_quantiles
    params:
      code_quantiles: ${default_if_null:${vocab},${output_dir}}/${quantiles_fn}

  - name: preprocessing
    transforms:
      # - BMIData.join_token_and_quantile # BMI dealt with as simple measurement
      - DiagnosesData.prepare_codes_for_processing
      - DiagnosesData.convert_icd_9_to_10
      - DiagnosesData.process_icd10
      - ProcedureData.prepare_codes_for_processing
      - ProcedureData.convert_icd_9_to_10
      - ProcedureData.process_icd10
      - MedicationData.convert_to_atc
    vocab: ${vocab}

  # Don't have static events now
  # - name: StaticDataCollector
  #   agg_to: ${output_dir}/static_data.pickle
  #   params:
  #     static_code_prefixes:
  #       - MEDS_BIRTH
  #       - GENDER
  #       - MARITAL
  #       - RACE
  #       - BMI

  # - name: filter_codes
  #   params:
  #     codes_to_remove:
  #       - MEDS_BIRTH
  #       - GENDER
  #       - MARITAL
  #       - RACE
  #     is_prefix: true

  - name: inject_time_intervals
    params:
      time_intervals_spec: ${time_intervals_spec}

  - name: IntervalEstimator
    params:
      time_intervals_spec: ${time_intervals_spec}
    agg_to: ${output_dir}/${intervals_fn}
    skip: ${is_not_null:${vocab}}

  - name: CodeCounter
    agg_to: ${output_dir}/${code_counts_fn}
