name: mimic
stages:

  - name: preprocessing
    transforms:
      - LabData.retain_only_test_with_numeric_result
      - TransferData.retain_only_transfer_and_admit_types
      - DemographicData.retrieve_demographics_from_hosp_adm
      - DemographicData.process_race
      - DemographicData.process_marital_status
      - InpatientData.process_drg_codes
      - InpatientData.process_hospital_admissions
      - InpatientData.process_hospital_discharges # must be before processing diagnoses
      - HCPCSData.unify_names
    vocab: ${vocab}

  - name: CodeCounter
    agg_to: ${output_dir}/${code_counts_fn}
    skip: ${is_not_null:${vocab}}

  - name: preprocessing_with_counts
    transforms:
      - LabData.make_quantiles
    params:
      counts: ${output_dir}/${code_counts_fn}
    vocab: ${vocab}

  - name: preprocessing
    transforms:
      - DeathData.place_death_before_dc_if_same_time
      - PatientFluidOutputData.make_quantiles
      - BMIData.make_quantiles
      - MeasurementData.process_simple_measurements
      - MeasurementData.process_pain
      - MeasurementData.process_blood_pressure
    vocab: ${vocab}

  - name: preprocessing_with_num_quantiles
    transforms:
      - ICUStayData.process
    params:
      num_quantiles: ${num_quantiles}
    vocab: ${vocab}

  - name: Quantizator
    params:
      code_prefixes:
        - LAB//Q//
        - BMI//Q
        - VITAL//Q//
        - SUBJECT_FLUID_OUTPUT//Q//
        - ED_ACUITY//Q
    agg_to: ${output_dir}/${quantiles_fn}
    agg_params:
      num_quantiles: ${num_quantiles}
    skip: ${is_not_null:${vocab}}

  - name: transform_to_quantiles
    params:
      code_quantiles: ${default_if_null:${vocab},${output_dir}}/${quantiles_fn}

  - name: preprocessing
    transforms:
      - BMIData.join_token_and_quantile
    vocab: ${vocab}

  - name: StaticDataCollector
    agg_to: ${output_dir}/static_data.pickle
    params:
      static_code_prefixes:
        - MEDS_BIRTH
        - GENDER
        - MARITAL
        - RACE
        - BMI

  - name: filter_codes
    params:
      codes_to_remove:
        - MEDS_BIRTH
        - GENDER
        - MARITAL
        - RACE
      is_prefix: true

  - name: apply_vocab
    params:
      vocab: ${vocab}

  - name: inject_time_intervals
    params:
      time_intervals_spec: ${time_intervals_spec}

  - name: IntervalEstimator
    params:
      time_intervals_spec: ${time_intervals_spec}
    agg_to: ${output_dir}/${intervals_fn}
    skip: ${is_not_null:${vocab}}

  - name: CodeCounter
    agg_to: ${output_dir}/${code_counts_fn}
