# Copied from https://github.com/ipolharvard/ethos-ares/blob/2d54383997318eb52f3d47b5969a66fc166b71ff/scripts/meds/mimic/configs/pre_MEDS.yaml

input_dir: ${oc.env:MIMICIV_RAW_DIR}
cohort_dir: ${oc.env:MIMICIV_PRE_MEDS_DIR}

do_overwrite: false

log_dir: ${cohort_dir}/.logs

# Hydra
hydra:
  job:
    name: pre_MEDS_${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: ${log_dir}
  sweep:
    dir: ${log_dir}
